name: OWASP Dependency Check

on:
  push:
    branches: [main]

jobs:
  dependency-check:
    name: Run OWASP Dependency Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'NewcomerAU'
          path: '.'
          format: 'HTML'
          out: 'reports'

      - name: Upload Dependency Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: reports