name: OWASP Dependency Check

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          cd server && npm install --legacy-peer-deps
          cd ../client && npm install --legacy-peer-deps

      - name: Install dependency-check
        run: |
          mkdir -p dependency-check
          curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip -o dc.zip
          unzip dc.zip -d dependency-check

      - name: Run OWASP Dependency Check
        run: |
          ./dependency-check/dependency-check/bin/dependency-check.sh \
            --project "OWASP Scan" \
            --scan ./ \
            --format HTML \
            --out ./owasp-report

      - name: Upload OWASP Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ./owasp-report/dependency-check-report.html