name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  deploy-backend:
    name: Deploy Node.js Backend with OCR Support
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy server/ folder to EC2 (upload to backend/)
        run: |
          set -e
          cd $GITHUB_WORKSPACE

          echo "Removing old backend on EC2..."
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "rm -rf ~/backend"

          echo "Uploading new backend files..."
          scp -r ./server ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/backend

      - name: Restart backend and clean temporary files
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            echo "Installing Node.js dependencies..."
            cd ~/backend
            npm install

            echo "Activating Python venv..."
            source ./ocr/venv/bin/activate

            echo "Cleaning temporary pip files..."
            sudo rm -rf /tmp/pip-* /tmp/tmp* /tmp/build* /tmp/easyocr*

            echo "Restarting backend with PM2 in production mode..."
            cd ~/backend
            pm2 restart ecosystem.config.js --env production || pm2 start index.js --name backend --env production

            echo "Saving PM2 state..."
            pm2 save
          EOF