name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main
      - iteration1
      - iteration2
      - iteration3
    paths:
      - 'client/**'

jobs:
  deploy-frontend:
    name: Deploy Vue Frontend to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy client folder to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "rm -rf ~/client"
          scp -r ./client ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/

      - name: Build on EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << EOF
            cd ~/client
            npm install
            npm run build

            BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
            if [ "$BRANCH_NAME" = "main" ]; then
              TARGET_DIR="/var/www/newcomerau/main"
            else
              TARGET_DIR="/var/www/newcomerau/$BRANCH_NAME"
            fi

            sudo mkdir -p \$TARGET_DIR
            sudo rm -rf \$TARGET_DIR/*
            sudo cp -r dist/* \$TARGET_DIR/
            sudo chown -R www-data:www-data \$TARGET_DIR
            sudo systemctl reload nginx
          EOF
