name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  deploy-backend:
    name: Deploy Node.js Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy server/ folder to EC2 (upload to backend/)
        run: |
          set -e
          cd $GITHUB_WORKSPACE

          # Remove old backend folder
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "rm -rf ~/backend"

          # Copy local server folder into backend directory
          scp -r ./server ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/backend

      - name: Install backend dependencies and restart server
        run: |
          set -e
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/backend
            echo "Installing backend dependencies..."
            npm install

            echo "Killing old Node server if running..."
            pkill -f "node index.js" || true

            echo "Starting new Node server..."
            nohup node index.js > ~/server.log 2>&1 &
          EOF
