name: Deploy iteration1 Frontend to EC2

on:
  push:
    branches:
      - iteration1
    paths:
      - 'client/**'

jobs:
  deploy-frontend:
    name: Deploy iteration1 to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy frontend project to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "rm -rf ~/client"
          scp -r ./client ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/

      - name: Build and deploy to /iteration1
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/client
            npm install
            npm run build

            sudo mkdir -p /var/www/newcomerau/iteration1
            sudo rm -rf /var/www/newcomerau/iteration1/*
            sudo cp -r dist/* /var/www/newcomerau/iteration1/
            sudo chmod -R 755 /var/www/newcomerau/iteration1
            sudo systemctl reload nginx
          EOF
