name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  deploy-backend:
    name: Deploy Node.js Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy server/ folder to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "rm -rf ~/server"
          scp -r ./server ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/

      - name: Install dependencies and restart backend
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/server
            npm install

            # Kill old server if running
            pkill -f "node index.js" || true

            # Run backend in background with logs
            nohup node index.js > ~/server.log 2>&1 &
          EOF