name: Deploy Frontend to AWS EC2 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # - name: List files in client (debug)
      #   run: ls -al
      #   working-directory: client

      - name: Install dependencies
        run: npm ci
        working-directory: client

      - name: Build project
        run: npm run build
        working-directory: client

      - name: Deploy to EC2 via SSH (prepare Nginx and clean up)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if ! command -v nginx &> /dev/null; then
              sudo apt-get update -y
              sudo apt-get install -y nginx
              sudo systemctl start nginx
              sudo systemctl enable nginx
            fi

            sudo mkdir -p /var/www/newcomerau
            sudo rm -rf /var/www/newcomerau/*
            sudo chown ubuntu:ubuntu /var/www/newcomerau

      - name: Copy built files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "client/dist/*"
          target: "/var/www/newcomerau"

      - name: Reload Nginx and fix permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo chown -R www-data:www-data /var/www/newcomerau
            sudo chmod -R 755 /var/www/newcomerau
            sudo nginx -t && sudo systemctl reload nginx
