name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  deploy-backend:
    name: Deploy Node.js Backend with OCR Support
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy server/ folder to EC2 (sync to ~/backend/)
        run: |
          rsync -av \
            --exclude 'logs' \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./server/ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/backend/

      - name: Install dependencies and restart backend
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            echo "Installing Node.js dependencies..."
            cd ~/backend
            npm install

            echo "Installing Python dependencies from requirements.txt..."
            pip install -r requirements.txt --no-cache-dir

            echo "Restarting backend with PM2 in production mode..."
            pm2 restart ecosystem.config.js --env production || pm2 start index.js --name backend --env production

            echo "Saving PM2 state..."
            pm2 save
          EOF