name: Gitleaks Secret Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gitleaks:
    name: Run Gitleaks Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks

      - name: Run Gitleaks scan
        run: |
           mkdir -p gitleaks-report
           gitleaks detect --source=. --no-git \
             --report-format=json \
             --report-path=gitleaks-report/gitleaks-report.json \
             --verbose || true


      - name: Upload Gitleaks Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report/gitleaks-report.json