name: Dependency Security Scan

on:
  push:
    branches: [main]
    paths:
      - 'server/**'
      - 'client/**'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    name: OWASP Dependency Check
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'newcomerau'
          path: './'
          format: 'HTML,JSON'

      - name: Upload report artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-reports
          path: |
            dependency-check-report.html
            dependency-check-report.json